# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurance',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.DeleteModel(
            name='insurance',
        ),
        migrations.DeleteModel(
            name='speciality',
        ),
    ]
