# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_year',
            new_name='bdate',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
