# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummyDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
                ('specialization', models.CharField(default=None, max_length=250)),
                ('insurance', models.CharField(default=None, max_length=250)),
                ('rating', models.IntegerField(default=0)),
                ('phoneNumber', models.IntegerField(default=1234567890)),
                ('address', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
