# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171129_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummydoctor',
            name='digit',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
