# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_dummydoctor_digit'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=250)),
                ('doctor_name', models.CharField(max_length=250)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='id_num',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
