# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20171129_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='scheduled_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
